In [31]:
#Create a numpy array
import numpy as np
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [32]:
#Reshape the array into a 2D array with 3x9
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [33]:
#Reshape the array into a 3D array 3x3x3
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
#Convert a normal list into a numpy array
arr = [[1,2,3,4,5,6,7,8,9],[0,2,4,6,8],[1,3,5,7,9]]
m = np.asarray(arr)
m

array([list([1, 2, 3, 4, 5, 6, 7, 8, 9]), list([0, 2, 4, 6, 8]),
       list([1, 3, 5, 7, 9])], dtype=object)

In [35]:
#openCV library (cv2) is used to read images into python
import cv2
#imread takes image path and 0/1 -> 0 = grayscale, 1 = BGR
im_g = cv2.imread("smallgray.png", 0) #-> Grayscale
#Image is saved as a numpy array where 255 is white and 0 is Black and all values between that are on the greyscale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [36]:
#imread takes image path and 0/1 -> 0 = grayscale, 1 = BGR
im_rgb = cv2.imread("smallgray.png", 1)#-> BGR
#3D array for B G R -> Transposed since we actually have 3 rows and 5 columns
im_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [37]:
#Creates an image from a numpy array
cv2.imwrite("newsmallgray.png", im_g)

True

In [38]:
#Indexing numpy arrays -> Give range of rows and columns for 2D array
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [39]:
#Gives r,c of array
im_g.shape

(3, 5)

In [40]:
#Row by row iteration
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [41]:
#To iterate column by column -> Transpose the array and then traverse
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [42]:
#.flat allows you to access elements one by one
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [47]:
#Stacking numpy arrays: Arrays have to be the same dimensions
#Stacking two np arrays horizontally
ims = numpy.hstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
#Stacking two np arrays vertically
ims = numpy.vstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
#Splitting arrays can be done horizontally or vertically but needs to be split equally
#Horizontal split
lst = np.hsplit(ims, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [51]:
#Vertical splitting
lst = np.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]